name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: zip, intl
          coverage: none

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Vendor cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-

      - name: Install dependencies
        env:
          COMPOSER_CACHE_DIR: ${{ runner.temp }}/composer-cache
        run: |
          composer config cache-dir $COMPOSER_CACHE_DIR
          composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run tests
        run: php -d memory_limit=2G bin/phpunit --testdox
